name: longevity_gpts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn
    - thefuzz
    - pycomfort>=0.0.15
    - polars>=1.3.0
    - hybrid_search>=0.0.15
    - psutil #compartibilit
    - loguru
    - httpx
    - just-agents>=0.2.5
    - litellm>=1.51.3
    - FlagEmbedding
    - eliot-tree
    - eliot
    - typer
    - gseapy
