name: gpt_rest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
    - fastapi
    - uvicorn
    - thefuzz
    - pycomfort>=0.0.15
    - pydantic==1.10.12
    - polars>=0.19.11
    - hybrid_search>=0.0.7 #for Future hybrid search API
    - psutil #compartibility
    - pydantic==1.10.12 #compartibility