name: longevity_gpts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
    - fastapi
    - uvicorn
    - thefuzz
    - pycomfort>=0.0.15
    - polars>=0.19.11
    - hybrid_search>=0.0.13 #for Future hybrid search API
    - psutil #compartibility
#    - pydantic==1.10.12 #compartibility
    - pydantic>=2.3.7
    - loguru
    - torch
    - httpx
    - just-agents>=0.0.7
