name: longevity_gpts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip:
    - fastapi
    - uvicorn
    - thefuzz
    - pycomfort>=0.0.15
    - polars>=1.3.0
    - hybrid_search>=0.0.15
    - psutil #compartibilit
    - loguru
    - httpx
    - just-agents>=0.1.0
    - litellm>=1.42.5
    - FlagEmbedding
    - eliottree
    - eliot
